### ISSUE TITLE
RBXSCRIPT.COM ON TOP BROO

### ISSUE THREAD

**Issue by Gelatekussy** [sinret/rbxscript.com-scripts-reuploads-#1]
RBXSCRIPT.COM ON TOP BROO 💀💀💀💀💀💀💀💀💀💀
RBXSCRIPT.COM ON TOP BROO 💀💀💀💀💀💀💀💀💀💀
RBXSCRIPT.COM ON TOP BROO 💀💀💀💀💀💀💀💀💀💀
RBXSCRIPT.COM ON TOP BROO 💀💀💀💀💀💀💀💀💀💀

**Comment by sinret** [comment]
ok and

**Comment by Gelatekussy** [comment]
![image](https://user-images.githubusercontent.com/76650942/202858576-e3e12a98-5046-4d4c-9204-79dfa108f22f.png)
how you feel like after editing the message
